name: WineQuality Checker

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt]; then pip install -r requirements.txt; fi
    - name: Test with Pytest
      run: |
        pytest -v

        
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: 
        HEROKU_APP_NAME
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        git remote add heroku 
        git push heroku 