name: WineQuality Checker

on:
  push:
    branches:
      - main
      - model-tracking
  pull_request:
    branches:
      - model-tracking
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug Python Path
        run: |
          echo "Python Path: $PYTHONPATH"
          ls -R  

      - name: Run Tests with Pytest
        run: |
          export PYTHONPATH=$(pwd)  
          pytest -v  
